name: CI
on:
  push:
    branches: main
jobs:
  sql:
    name: "Update database in production"
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Update and upgrade host
        run: |
          apt update
          apt install -y postgresql-client
      - name: Git clone locally
        run: |
          git clone https://github.com/gaahfy/langtools
      - name: Create .pgpass file
        run: |
          cat > ~/.pgpass << EOF
            ${{ secrets.PRODUCTION_SQL_HOST }}:${{ secrets.PRODUCTION_SQL_PORT }}:${{ secrets.PRODUCTION_SQL_DATABASE }}:${{ secrets.PRODUCTION_SQL_USERNAME }}:${{ secrets.PRODUCTION_SQL_PASSWORD }}
          EOF
      - name: Update database in production
        run: |
          psql -U ${{ secrets.PRODUCTION_SQL_USERNAME }} -d ${{ secrets.PRODUCTION_SQL_DATABASE }} -h ${{ secrets.PRODUCTION_SQL_HOST }} -p ${{ secrets.PRODUCTION_SQL_PORT }} -a -q -f ~/langtools/sql/update.sql
  deploy:
    name: "Deploy backend to production"
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRODUCTION_BACKEND_SSH_KEY }}" > ~/.ssh/production.key
          chmod 600 ~/.ssh/production.key
          cat > ~/.ssh/config << EOF
          Host production
            HostName ${{ secrets.PRODUCTION_BACKEND_SSH_HOST }}
            User ${{ secrets.PRODUCTION_BACKEND_SSH_USER }}
            IdentityFile ~/.ssh/production.key
            StrictHostKeyChecking no
          EOF
      - name: Git clone locally
        run: |
          git clone https://github.com/gaahfy/langtools
      - name: Build Server locally
        run: |
          cd langtools/backend && go mod tidy && GOOS=linux GOARCH=amd64 go build server.go
      - name: Switch down server in production
        run: |
          ssh production 'sudo systemctl stop langtools-backend.service'
      - name: Remove current version of the server in production
        run: |
          ssh production 'touch /home/admin/server && rm /home/admin/server'
      - name: Move version of the server built locally to production
        run: |
          scp ./langtools/backend/server production:/home/admin
          ssh production 'mkdir -p /home/admin/letsencrypt'
      - name: Switch up server in production
        run: |
          ssh production 'sudo systemctl start langtools-backend.service'
